Repository 2025KAU-MAITE/BE, pull requests merged in 2025-05, with the labels that each got.

#16 [FEAT] 구글 stt 기반 회의록 요약 구현
  .gitignore
  build.gradle
  src/main/java/maite/maite/service/OpenAIService.java
  src/main/java/maite/maite/service/SpeechToTextService.java
  src/main/java/maite/maite/web/controller/SpeechSummaryController.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#17 protobuf 의존성 추가(stt)
  build.gradle
Labels: :bug: bugfix

#27 [BugFix] GCP 크리덴셜 버그 수정
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/maite/maite/config/GcpConfig.java
  src/main/java/maite/maite/service/SpeechToTextService.java
  src/main/resources/application.yml
Labels: :bug: bugfix

#29 s3 수정
  build.gradle
  src/main/java/maite/maite/aws/S3/AmazonS3Manager.java
  src/main/java/maite/maite/aws/S3/Uuid.java
  src/main/java/maite/maite/aws/S3/UuidRepository.java
  src/main/java/maite/maite/config/AmazonConfig.java
  src/main/java/maite/maite/config/SwaggerConfig.java
  src/main/java/maite/maite/domain/entity/chat/Message.java
  src/main/java/maite/maite/service/S3Service.java
  src/main/java/maite/maite/web/controller/chat/ChatController.java
Labels: :bug: bugfix

#35 친구(mate)기능 구현
  src/main/java/maite/maite/domain/entity/Mate.java
  src/main/java/maite/maite/repository/MateRepository.java
  src/main/java/maite/maite/service/mate/MateService.java
  src/main/java/maite/maite/service/mate/MateServiceImpl.java
  src/main/java/maite/maite/service/timetable/TimetableServiceImpl.java
  src/main/java/maite/maite/web/controller/MateController.java
  src/main/java/maite/maite/web/dto/mate/request/MateRequestDto.java
  src/main/java/maite/maite/web/dto/mate/request/UserSearchRequestDto.java
  src/main/java/maite/maite/web/dto/mate/response/MateResponseDto.java
  src/main/java/maite/maite/web/dto/mate/response/UserSearchResponseDto.java
Labels: :sparkles: feature

#39 [FEAT] 타 유저 시간표 조회기능 추가
  src/main/java/maite/maite/service/timetable/TimetableService.java
  src/main/java/maite/maite/service/timetable/TimetableServiceImpl.java
  src/main/java/maite/maite/web/controller/timetable/TimetableController.java
  src/main/java/maite/maite/web/dto/timetable/request/UserTimetableRequestDto.java
  src/main/java/maite/maite/web/dto/timetable/response/UserTimetableResponseDto.java
Labels: :sparkles: feature

#36 [FEAT] AI 호출 기능 구현
  build.gradle
  src/main/java/maite/maite/service/AI/ConvertToWavService.java
  src/main/java/maite/maite/service/AI/OpenAIService.java
  src/main/java/maite/maite/service/AI/SpeechToTextService.java
  src/main/java/maite/maite/service/AI/TextToSpeechService.java
  src/main/java/maite/maite/web/controller/SpeechSummaryController.java
  src/main/java/maite/maite/web/controller/auth/AuthController.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#46 채팅 내역 조회 기능 추가
  src/main/java/maite/maite/repository/chat/MessageRepository.java
  src/main/java/maite/maite/service/chat/ChatService.java
  src/main/java/maite/maite/service/chat/ChatServiceImpl.java
  src/main/java/maite/maite/web/controller/chat/ChatController.java
  src/main/java/maite/maite/web/controller/chat/ChatRoomController.java
Labels: :sparkles: feature

#41 [Refactor] 유저 프로필이미지 기능 구현, 수정
  src/main/java/maite/maite/apiPayload/code/status/ErrorStatus.java
  src/main/java/maite/maite/repository/UserRepository.java
  src/main/java/maite/maite/service/S3Service.java
  src/main/java/maite/maite/service/auth/AuthServiceImpl.java
  src/main/java/maite/maite/service/auth/SmsUtil.java
  src/main/java/maite/maite/web/controller/auth/AuthController.java
  src/main/java/maite/maite/web/dto/User/ErrorResponse.java
  src/main/java/maite/maite/web/dto/User/RefreshTokenRequest.java
  src/main/java/maite/maite/web/dto/User/Signup/SignupRequestDTO.java
Labels: :sparkles: feature, :recycle: refactor

#48 [FEAT] 구글 로그인 구현(프론트)
  build.gradle
  src/main/java/maite/maite/config/SecurityConfig.java
  src/main/java/maite/maite/security/GoogleTokenUtil.java
  src/main/java/maite/maite/service/auth/AuthService.java
  src/main/java/maite/maite/service/auth/AuthServiceImpl.java
  src/main/java/maite/maite/web/controller/auth/AuthController.java
  src/main/java/maite/maite/web/dto/User/Login/GoogleLoginRequest.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#51 [FEAT] 카카오페이 임시 결제 구현
  src/main/java/maite/maite/config/AppConfig.java
  src/main/java/maite/maite/config/SecurityConfig.java
  src/main/java/maite/maite/service/pay/KakaoPayService.java
  src/main/java/maite/maite/service/pay/KakaoPayServiceImpl.java
  src/main/java/maite/maite/web/controller/pay/KakaoPayController.java
  src/main/java/maite/maite/web/dto/pay/KakaoPayApproveRequest.java
  src/main/java/maite/maite/web/dto/pay/KakaoPayApproveResponse.java
  src/main/java/maite/maite/web/dto/pay/KakaoPayReadyResponse.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#58 [FEAT] 프로필이미지 변경 구현
  src/main/java/maite/maite/aws/S3/AmazonS3Manager.java
  src/main/java/maite/maite/service/S3Service.java
  src/main/java/maite/maite/web/controller/ProfileController.java
  src/main/java/maite/maite/web/controller/pay/KakaoPayController.java
Labels: :sparkles: feature

#59 단일 시간표로 수정, 일정 안보이는 버그 수정
  src/main/java/maite/maite/repository/timetable/TimetableRepository.java
  src/main/java/maite/maite/service/timetable/EventService.java
  src/main/java/maite/maite/service/timetable/EventServiceImpl.java
  src/main/java/maite/maite/service/timetable/TimetableService.java
  src/main/java/maite/maite/service/timetable/TimetableServiceImpl.java
  src/main/java/maite/maite/web/controller/timetable/EventController.java
  src/main/java/maite/maite/web/controller/timetable/TimetableController.java
Labels: :bug: bugfix

#61 [FEAT] 유저 엔티티 결제 여부 로직 추가
  src/main/java/maite/maite/domain/entity/Subscription.java
  src/main/java/maite/maite/domain/entity/User.java
  src/main/java/maite/maite/repository/SubscriptionRepository.java
  src/main/java/maite/maite/service/pay/SubsciptionServiceImpl.java
  src/main/java/maite/maite/service/pay/SubscriptionService.java
  src/main/java/maite/maite/web/controller/auth/AuthController.java
  src/main/java/maite/maite/web/controller/pay/KakaoPayController.java
  src/main/java/maite/maite/web/dto/User/InfoResponse.java
Labels: :sparkles: feature, :recycle: refactor

#64 액세스 권한 코드 추가
  src/main/java/maite/maite/web/controller/chat/ChatController.java
Labels: :bug: bugfix

#66 토스 결제 기능 구현
  src/main/java/maite/maite/config/SecurityConfig.java
  src/main/java/maite/maite/service/pay/TossPayService.java
  src/main/java/maite/maite/service/pay/TossPayServiceImpl.java
  src/main/java/maite/maite/web/controller/pay/TossPayController.java
  src/main/java/maite/maite/web/dto/pay/TossPayApproveRequest.java
  src/main/java/maite/maite/web/dto/pay/TossPayApproveResponse.java
  src/main/java/maite/maite/web/dto/pay/TossPayReadyResponse.java
  src/main/resources/application.yml
  src/main/resources/static/test-toss.html
Labels: :sparkles: feature

#67 [FEAT] 네이버 클로바 기능 기초 구현 및 로그인 반환 형태 수정
  src/main/java/maite/maite/service/AI/ClovaSpeechService.java
  src/main/java/maite/maite/service/AI/ObjectStorageService.java
  src/main/java/maite/maite/web/controller/SpeechSummaryController.java
  src/main/java/maite/maite/web/controller/auth/AuthController.java
  src/main/java/maite/maite/web/dto/AI/ClovaResult.java
  src/main/java/maite/maite/web/dto/AI/SpeechRequest.java
  src/main/java/maite/maite/web/dto/User/Login/LoginResponse.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#68 채팅 엑세스 권한 제거
  src/main/java/maite/maite/web/controller/chat/ChatController.java
Labels: :bug: bugfix

#70 s3매니저 사진 조회 버그 수정
  src/main/java/maite/maite/aws/S3/AmazonS3Manager.java
Labels: :bug: bugfix

#71 네이버 클로바 기능 수정 및 회의록 저장 구현
  src/main/java/maite/maite/repository/meeting/MeetingRepository.java
  src/main/java/maite/maite/web/controller/SpeechSummaryController.java
Labels: :sparkles: feature

#73 alb 준비
  build.gradle
  src/main/java/maite/maite/config/SecurityConfig.java
  src/main/java/maite/maite/web/controller/HealthController.java
Labels: :sparkles: feature
